LDBR-2.21: Страница доски
frontend-park-mail-ru/2021_2_LadnoDavayteBezRoflov pull request #25
Opened 2021-10-30 18:37 UTC by DPeshkoff

2021-11-01 13:04 UTC, DPeshkoff commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница доски [2.21]](https://trello.com/c/bzdf4SRF/58-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%B4%D0%BE%D1%81%D0%BA%D0%B8-221)

2021-11-06 10:35 UTC, gavroman commented on src/actions/boards.js
> +                id: id,
`data: {id}`

2021-11-06 10:35 UTC, gavroman commented on src/actions/boards.js
> +                teamID: teamID,
?

2021-11-06 10:36 UTC, gavroman commented on src/actions/card.js
> +    createCard(id, clid, position, title, description, deadline, checklist,
давай в объект все

2021-11-06 10:36 UTC, gavroman commented on src/actions/card.js
> +                attachments: attachments,
data: {id, clid, position .....}

2021-11-06 10:36 UTC, gavroman commented on src/actions/card.js
> +        assignees, tags, attachments) {
тут тоже много параметров

2021-11-06 10:37 UTC, gavroman commented on src/components/Card/Card.js
> +            deadline: undefined,
null

2021-11-10 08:01 UTC, gavroman commented on src/components/Footer/Footer.js
> +        super(context, template, undefined);
тык

2021-11-10 08:02 UTC, gavroman commented on src/components/Navbar/Navbar.js
> +        super(context, template, undefined);
и тут

2021-11-10 08:18 UTC, gavroman requested changes

2021-11-10 08:18 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +                this._getCardListById(clid));
a.findIndex(({id}) => id === 3)

2021-11-10 08:18 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +            const index = cards.indexOf(
a.findIndex(({id}) => id === 3)

2021-11-10 08:18 UTC, gavroman commented on src/views/BoardView/BoardView.scss
> +    //max-width: 1680px;
?

2021-11-10 08:18 UTC, gavroman commented on src/views/BoardView/BoardView.scss
> +    //margin: 0 auto;
?

2021-11-10 08:18 UTC, gavroman commented on src/views/BoardView/BoardView.scss
> +    //flex-basis: 100%;
?

2021-11-10 09:28 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +            throw new Error(`BoardStore: карточка ${cidForDeletion} не найдена.`);
давай лучше ошибку в ифаке кидать, тут и в _deleteCardList тоже

2021-11-10 09:39 UTC, gavroman approved these changes

2021-11-10 09:39 UTC, merged