LDBR-2.27: Исправить карточки
frontend-park-mail-ru/2021_2_LadnoDavayteBezRoflov pull request #30
Opened 2021-11-09 01:42 UTC by DPeshkoff

2021-11-09 01:57 UTC, DPeshkoff commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обработчики карточки + модальное окно [2.27]](https://trello.com/c/eLL1ZcNM/65-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B8-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B8-%D0%BC%D0%BE%D0%B4%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%BA%D0%BD%D0%BE-227)

2021-11-09 06:31 UTC, gavroman commented on package.json
> +        "server": "node server/server.js",
?

2021-11-09 07:12 UTC, gavroman requested changes

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +            cardLists.splice(index, 1);
indexOf если не найдет, то вернет -1
> [1,2,3,4,5].slice(-1,1)
[]

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +                this._getCardListById(this._storage.get('delete-cl-popup').clid));
Давай за красоту поборемся, сначала достанем: `const {clid} = this._storage.get('delete-cl-popup')`, потом будем искать. Чтоб искать, не обязательно доставать всю карточку, можно заюзать findIndex, он принимает функу

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +        console.log(data);
тык

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +        cardPopup.errors = null;
тут нельзя весь объект сраз уприсваивать?

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +            });
копипаста, давай выносить общую логику

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +        this._storage.get('delete-card-popup').card_name =
тут нельзя весь объект сраз уприсваивать?

2021-11-09 07:12 UTC, gavroman commented on src/stores/BoardStore/BoardStore.js
> +            cards.splice(index, 1);
тут то же самое, что и в удилении списка

2021-11-09 07:12 UTC, gavroman commented on src/views/BoardView/BoardView.hbs
> +{{{DeleteCardPopUp}}}
?

2021-11-09 07:12 UTC, gavroman commented on src/views/BoardView/BoardView.js
> +        this.addComponent('DeleteCardPopUp', new DeleteCardPopUp());
подлей еще разок ветку со списками, там это уже починили

2021-11-09 07:12 UTC, gavroman commented on src/views/BoardView/BoardView.js
> +        // todo карточки и так массивом идут
что за туду

2021-11-09 07:12 UTC, gavroman commented on src/views/BoardView/BoardView.js
> +        console.log('cid', parseInt(event.target.dataset.id, 10));
атата

2021-11-09 07:12 UTC, gavroman commented on src/views/BoardView/BoardView.js
> +        console.log('eventTarget: ', event.target);
атата х2

2021-11-09 07:12 UTC, gavroman commented on src/views/ProfileView/ProfileView.js
> +        console.log(UserStore.getContext('userName').login);
а пароль покажешь?))

2021-11-09 07:24 UTC, DPeshkoff commented on package.json
> +        "server": "node server/server.js",
нужно для запуска на 80 порту

2021-11-09 07:24 UTC, DPeshkoff commented on src/modules/Helpers/isEmptyDeadlineHelper.js
> +        if (deadline === '0001-01-01T00:00:00Z') {
время по умолчанию - на него нужно тоже проверять

2021-11-09 07:26 UTC, DPeshkoff commented on src/modules/Network/Network.js
> +            body: JSON.stringify(data),
на 41 строке вливаются

'Content-Type' не дефолтный, потому что мы еще файлы посылаем

2021-11-09 07:28 UTC, DPeshkoff commented on src/stores/BoardStore/BoardStore.js
> +        this._storage.get('setting-popup').confirm = true;
есть,

`{
            visible: false,
            board_name: null,
            description: null,
            errors: null,
            confirm: false,
        }`

2021-11-09 07:43 UTC, DPeshkoff commented on src/stores/BoardStore/BoardStore.js
> +            });
раньше был баг, когда предпоследний элемент не сдвигался, а с этим фиксом оно работает

2021-11-09 07:53 UTC, DPeshkoff commented on src/views/BoardView/BoardView.hbs
> +{{{DeleteCardPopUp}}}
нужно для отрисовки

2021-11-09 07:53 UTC, DPeshkoff commented on src/views/BoardView/BoardView.js
> +        this.addComponent('DeleteCardPopUp', new DeleteCardPopUp());
там как раз так и создается

2021-11-10 07:13 UTC, gavroman commented on src/modules/Helpers/isEmptyDeadlineHelper.js
> +        if (deadline === '0001-01-01T00:00:00Z') {
тогда давай его в окнстанту

2021-11-10 07:40 UTC, merged