LDBR-3.17: Дедлайн
frontend-park-mail-ru/2021_2_LadnoDavayteBezRoflov pull request #34
Opened 2021-11-15 12:41 UTC by DPeshkoff

2021-11-15 12:41 UTC, DPeshkoff commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обновить карточку (дедлайн) [3.17]](https://trello.com/c/QoLHhD5e/83-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D1%83-%D0%B4%D0%B5%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD-317)

2021-11-16 20:39 UTC, GeorgiyX requested changes

2021-11-16 20:39 UTC, GeorgiyX commented on src/components/Card/Card.hbs
> +            <div class="badge-due-date-wrapper badge-due-date__text__{{deadlineStatus}} checkDeadlineCard" data-id="{{cid}}">
[Тут](https://ru.bem.info/methodology/quick-start/#%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C-1) написано, что в БЭМ не может быть элементов у элементов (т.е. двух `__` в имени класса не может быть).

2021-11-22 18:49 UTC, DPeshkoff commented
TODO: 

- [ ] автоматически обновлять дедлайн при изменении
- [ ] запретить большие года при вводе
- [ ] автоматически добавлять текущее время, если оно не введено

2021-11-23 20:52 UTC, TonyBlock approved these changes

2021-11-23 22:19 UTC, GeorgiyX approved these changes

2021-11-23 23:16 UTC, Trollbump approved these changes

2021-11-24 09:44 UTC, merged