Ldbr 3.1 navbar avatar
frontend-park-mail-ru/2021_2_LadnoDavayteBezRoflov pull request #35
Opened 2021-11-15 19:58 UTC by GeorgiyX

2021-11-15 20:05 UTC, GeorgiyX commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обновить Navbar [3.1]](https://trello.com/c/rhOIAs1H/69-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-navbar-31)

2021-11-15 20:17 UTC, DPeshkoff requested changes

2021-11-15 20:17 UTC, DPeshkoff commented on src/components/Navbar/Navbar.hbs
> +                        <span id="navbarUserNameId" class="">{{userName}}</span>
`class=""`

2021-11-15 20:17 UTC, DPeshkoff commented on src/styles/scss/Common.scss
> +  //min-width: 400px;
комментарий какой-то

2021-11-15 20:17 UTC, DPeshkoff commented on src/views/LoginView/LoginView.js
> +import SettingsStore from '../../stores/SettingsStore/SettingsStore';
закинь на строчку 11, чтобы в секцию _stores_

2021-11-15 20:18 UTC, yletamitlu commented on src/components/Navbar/Navbar.scss
> +        height: 56px;
а может все такое в константы?

2021-11-15 20:23 UTC, yletamitlu commented on src/components/Navbar/Navbar.scss
> +            background-color: rgba(0, 0, 0, 0.5);
особенно цвета

2021-11-15 20:23 UTC, yletamitlu commented on src/index.js
> +        if (UserStore.getContext('isAuthorized') === undefined) {
а тут нельзя !UserStore.getContext('isAuthorized')?

2021-11-15 20:23 UTC, yletamitlu commented on src/index.js
> +        try {
как будто хочется отступ перед этой строкой

2021-11-15 20:23 UTC, yletamitlu commented on src/views/BoardView/BoardView.js
> +        const context = new Map([...UserStore.getContext(), ...BoardStore.getContext(),
тут можно 
[
    1,
    2,
    3,
]);

ну ты понял, а то как-то не очень, два там, один тут

2021-11-15 20:23 UTC, yletamitlu commented on src/views/BoardView/BoardView.js
> +        this._setContext(new Map([...UserStore.getContext(), ...BoardStore.getContext(),
то же самое

2021-11-16 06:01 UTC, DPeshkoff commented on src/index.js
> +        if (UserStore.getContext('isAuthorized') === undefined) {
здесь нужна конкретно проверка на `undefined` — на неопределенное состояние, которое существует до получения результатов запроса `fetchUser`. После получения у нас становится либо false, либо true.

2021-11-16 07:29 UTC, gavroman commented on src/components/Navbar/Navbar.hbs
> +                             src="{{#if avatar}}{{avatar}}{{else}}/assets/nodata.webp{{/if}}"
давай дефолтную аву определим где-то в сторе, или во вьюхе хотя бы

2021-11-16 07:30 UTC, gavroman commented on src/components/Navbar/Navbar.hbs
> +                             src="{{#if avatar}}{{avatar}}{{else}}/assets/nodata.webp{{/if}}"
то есть этот ифак унесем куда-то выше

2021-11-16 19:29 UTC, GeorgiyX commented on src/components/Navbar/Navbar.hbs
> +                        <span id="navbarUserNameId" class="">{{userName}}</span>
Ок

2021-11-16 19:32 UTC, GeorgiyX commented on src/styles/scss/Common.scss
> +  //min-width: 400px;
Ок

2021-11-16 19:32 UTC, GeorgiyX commented on src/views/LoginView/LoginView.js
> +import SettingsStore from '../../stores/SettingsStore/SettingsStore';
Точно

2021-11-16 19:39 UTC, GeorgiyX commented on src/components/Navbar/Navbar.scss
> +        height: 56px;
Поправил

2021-11-16 19:39 UTC, GeorgiyX commented on src/components/Navbar/Navbar.scss
> +            background-color: rgba(0, 0, 0, 0.5);
Да

2021-11-16 19:57 UTC, GeorgiyX commented on src/index.js
> +        try {
Добавил

2021-11-16 19:58 UTC, GeorgiyX commented on src/views/BoardView/BoardView.js
> +        const context = new Map([...UserStore.getContext(), ...BoardStore.getContext(),
Ага

2021-11-16 19:58 UTC, GeorgiyX commented on src/views/BoardView/BoardView.js
> +        this._setContext(new Map([...UserStore.getContext(), ...BoardStore.getContext(),
Ок

2021-11-16 19:59 UTC, GeorgiyX commented on src/components/Navbar/Navbar.hbs
> +                             src="{{#if avatar}}{{avatar}}{{else}}/assets/nodata.webp{{/if}}"
Можно дать значение по умолчанию `/assets/nodata.webp` для `avatar` ключа в сторе.

2021-11-16 20:23 UTC, GeorgiyX commented on src/components/Navbar/Navbar.hbs
> +                             src="{{#if avatar}}{{avatar}}{{else}}/assets/nodata.webp{{/if}}"
Поставил nodata.webp как дефолтное значение в для avatar в SettingsStor'e. В принципе if'ы не нужны - мы от бека  всегда какую-нибудь аву получаем.

2021-11-16 20:42 UTC, DPeshkoff approved these changes

2021-11-17 07:35 UTC, gavroman approved these changes

2021-11-17 18:17 UTC, merged